# Generated by Django 5.1.6 on 2025-03-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='effectiveness_addiction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
