# Generated by Django 5.1.6 on 2025-11-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='wage',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
