# Generated by Django 5.1.6 on 2025-03-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_employee_effectiveness_addiction_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
    ]
