# Generated by Django 5.1.7 on 2025-11-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_add_wage_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
