# Generated by Django 5.1.6 on 2025-12-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_auto_now_add_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('company_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='company_cur_user_id_e24ec4_idx'), models.Index(fields=['company_id'], name='company_cur_company_fae1b4_idx')],
                'unique_together': {('user_id', 'company_id')},
            },
        ),
    ]
