# Generated by Django 5.1.6 on 2025-12-29 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_currentemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEmployeeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('wage', models.BigIntegerField(blank=True, null=True)),
                ('manual_labour', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('endurance', models.IntegerField()),
                ('effectiveness_working_stats', models.IntegerField()),
                ('effectiveness_settled_in', models.IntegerField()),
                ('effectiveness_merits', models.IntegerField(default=0)),
                ('effectiveness_director_education', models.IntegerField()),
                ('effectiveness_management', models.IntegerField()),
                ('effectiveness_inactivity', models.IntegerField()),
                ('effectiveness_addiction', models.IntegerField(default=0)),
                ('effectiveness_total', models.IntegerField()),
                ('last_action_status', models.CharField(max_length=255)),
                ('last_action_timestamp', models.DateTimeField()),
                ('last_action_relative', models.CharField(max_length=255)),
                ('status_description', models.CharField(max_length=255)),
                ('status_state', models.CharField(max_length=255)),
                ('status_until', models.DateTimeField(blank=True, null=True)),
                ('snapshot_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'ordering': ['-snapshot_date', 'employee_id'],
                'indexes': [models.Index(fields=['employee_id', 'snapshot_date'], name='company_dai_employe_268346_idx'), models.Index(fields=['company', 'snapshot_date'], name='company_dai_company_c154d6_idx'), models.Index(fields=['snapshot_date'], name='company_dai_snapsho_ae0273_idx')],
                'unique_together': {('company', 'employee_id', 'snapshot_date')},
            },
        ),
    ]
