# Generated by Django 5.1.7 on 2025-12-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_dailyemployeesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemployeesnapshot',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
