# Generated by Django 5.1.7 on 2025-12-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_dailyemployeesnapshot_modified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemployeesnapshot',
            name='in_switzerland',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyemployeesnapshot',
            name='last_travelled_to_switzerland',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyemployeesnapshot',
            name='returning_from_switzerland',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
