# Generated by Django 5.1.6 on 2026-01-02 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_dailyemployeesnapshot_in_switzerland_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyemployeesnapshot',
            options={'ordering': ['-snapshot_date', 'name']},
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.BigIntegerField()),
                ('rrp', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('in_stock', models.BigIntegerField()),
                ('on_order', models.BigIntegerField()),
                ('sold_amount', models.BigIntegerField()),
                ('sold_worth', models.BigIntegerField()),
                ('snapshot_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'ordering': ['-snapshot_date', 'name'],
                'indexes': [models.Index(fields=['company', 'snapshot_date'], name='company_sto_company_0d258c_idx'), models.Index(fields=['snapshot_date'], name='company_sto_snapsho_86e144_idx')],
                'unique_together': {('company', 'name', 'snapshot_date')},
            },
        ),
    ]
