# Generated by Django 5.1.7 on 2026-01-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_dailyemployeesnapshot_options_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_amount',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
