# Generated by Django 5.1.6 on 2026-01-02 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_stock_created_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.BigIntegerField(blank=True, null=True)),
                ('rrp', models.BigIntegerField(blank=True, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('in_stock', models.BigIntegerField(blank=True, null=True)),
                ('on_order', models.BigIntegerField(blank=True, null=True)),
                ('created_amount', models.BigIntegerField(blank=True, null=True)),
                ('sold_amount', models.BigIntegerField(blank=True, null=True)),
                ('sold_worth', models.BigIntegerField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('efficiency', models.IntegerField(blank=True, null=True)),
                ('environment', models.IntegerField(blank=True, null=True)),
                ('advertising_budget', models.BigIntegerField(blank=True, null=True)),
                ('trains_available', models.IntegerField(blank=True, null=True)),
                ('company_size', models.IntegerField(blank=True, null=True)),
                ('staffroom_size', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_size', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_space', models.BigIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['company', 'snapshot_date'], name='company_sal_company_083f74_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['snapshot_date'], name='company_sal_snapsho_db1c9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('company', 'snapshot_date')},
        ),
    ]
