# Generated by Django 5.1.6 on 2026-01-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_sale_delete_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='advertising_7day',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='annualized_roi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='daily_profit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='profit_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='stock_drift',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='value_generated',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='wages',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
