# Generated by Django 5.1.6 on 2026-01-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_sale_advertising_7day_sale_annualized_roi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='advertising_7day',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='annualized_roi',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='daily_profit',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='profit_margin',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='stock_drift',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='value_generated',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='wages',
        ),
    ]
