# Generated by Django 5.1.6 on 2026-01-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_remove_sale_advertising_7day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='wages',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
