# Generated by Django 5.1.6 on 2026-01-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_sale_wages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='wages',
        ),
    ]
