# Generated by Django 5.1.7 on 2025-03-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rackets',
            name='faction',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rackets',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rackets',
            name='reward',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rackets',
            name='territory',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
