# Generated by Django 5.1.6 on 2025-03-25 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='faction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='tag',
        ),
        migrations.AlterField(
            model_name='faction',
            name='faction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.factionlist', to_field='faction_id'),
        ),
    ]
