# Generated by Django 5.1.7 on 2025-03-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0002_faction_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='temp_field',
        ),
    ]
