# Generated by Django 5.1.7 on 2025-03-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0003_remove_faction_temp_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='factionlist',
            name='rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
