# Generated by Django 5.1.7 on 2025-03-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0004_factionlist_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
