# Generated by Django 5.1.6 on 2025-04-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0006_remove_factionlist_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisedCrimesRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('cpr', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
