# Generated by Django 5.1.6 on 2025-04-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0007_organisedcrimesroles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganisedCrimesRoles',
            new_name='OrganisedCrimeRole',
        ),
    ]
