# Generated by Django 5.1.7 on 2025-04-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0009_organisedcrimerole_crime_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisedcrimerole',
            old_name='cpr',
            new_name='required_cpr',
        ),
    ]
