# Generated by Django 5.1.6 on 2025-09-09 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TornUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tornuser', models.CharField(help_text='Torn username', max_length=255)),
                ('tornapi', models.CharField(help_text='Torn API key', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torn_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Torn User Profile',
                'verbose_name_plural': 'Torn User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
