# Generated by Django 5.1.7 on 2025-04-30 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0010_rename_cpr_organisedcrimerole_required_cpr'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrganisedCrimeCPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_cpr', models.IntegerField(blank=True, null=True)),
                ('organised_crime_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.organisedcrimerole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userlist')),
            ],
            options={
                'unique_together': {('user', 'organised_crime_role')},
            },
        ),
    ]
